### ISSUE TITLE
Error al Pagar Alerta Roja sin ningun valor

### ISSUE THREAD

**Issue by quesad300** [Gazer/px-flutter#10]
Lo que te agrega es lo que esta en rojo? No termino de entender.

_Originally posted by @Gazer in https://github.com/Gazer/px-flutter/issues/8#issuecomment-686787935_

Gazer al parecer es porq ocupe ya los correos de los usuarios de mi plataforma y no ocupe este payer@email.com, ahora tengo una duda al recibir pagos ¿el correo debe ser de una cuenta de mercado pago o sea no puede ser una q no este registrada en mercado pago?

ya que en la documentacion de mercado pago dice que tengo que crear una cuenta de prueba tanto como vendedor y comprador.

**Comment by pgivisiez** [comment]
esto también me está pasando a mí. encontró alguna solución?

**Comment by pgivisiez** [comment]
I found the problem here. Within the preferences data, I was using the same customer data (email, id) that was used by my seller account. Generated an error:

![image](https://user-images.githubusercontent.com/56278333/101421418-064e9400-38d3-11eb-8fb4-55034a43b9e4.png)

So I switched to another user data and it worked

**Comment by Gazer** [comment]
Closing because @pgivisiez found the problem.
